In [1]:
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

import tensorflow
from keras.layers import Dense
from keras.models import Sequential

In [2]:
dataset = pd.read_csv(r'dataset\employee_attrition_data.csv')

In [3]:
dataset.head(5)

,Employee_ID,Age,Gender,Department,Job_Title,Years_at_Company,Satisfaction_Level,Average_Monthly_Hours,Promotion_Last_5Years,Salary,Attrition
0,0,27,Male,Marketing,Manager,9,0.586251,151,0,60132,0
1,1,53,Female,Sales,Engineer,10,0.261161,221,1,79947,0
2,2,59,Female,Marketing,Analyst,8,0.304382,184,0,46958,1
3,3,42,Female,Engineering,Manager,1,0.480779,242,0,40662,0
4,4,44,Female,Sales,Engineer,10,0.636244,229,1,74307,0

In [4]:
dataset.shape

(1000, 11)

In [5]:
dataset.isnull().sum()

Employee_ID              0
Age                      0
Gender                   0
Department               0
Job_Title                0
Years_at_Company         0
Satisfaction_Level       0
Average_Monthly_Hours    0
Promotion_Last_5Years    0
Salary                   0
Attrition                0
dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
dataset['Department_encoded'] = le.fit_transform(dataset['Department'])
dataset['Job_Title_encoded'] = le.fit_transform(dataset['Job_Title'])

In [7]:
dataset['Department'].value_counts(), dataset['Department_encoded'].value_counts()

(Department
 Sales          209
 Finance        206
 Engineering    204
 HR             191
 Marketing      190
 Name: count, dtype: int64,
 Department_encoded
 4    209
 1    206
 0    204
 2    191
 3    190
 Name: count, dtype: int64)

In [8]:
dataset['Job_Title'].value_counts(), dataset['Job_Title_encoded'].value_counts()

(Job_Title
 Engineer         214
 Manager          206
 Accountant       206
 Analyst          195
 HR Specialist    179
 Name: count, dtype: int64,
 Job_Title_encoded
 2    214
 4    206
 0    206
 1    195
 3    179
 Name: count, dtype: int64)

In [9]:
dataset = pd.get_dummies(dataset, columns=['Gender'], drop_first=True)

dataset['Gender_Male'] = dataset['Gender_Male'].astype(int)

In [10]:
dataset.head()

,Employee_ID,Age,Department,Job_Title,Years_at_Company,Satisfaction_Level,Average_Monthly_Hours,Promotion_Last_5Years,Salary,Attrition,Department_encoded,Job_Title_encoded,Gender_Male
0,0,27,Marketing,Manager,9,0.586251,151,0,60132,0,3,4,1
1,1,53,Sales,Engineer,10,0.261161,221,1,79947,0,4,2,0
2,2,59,Marketing,Analyst,8,0.304382,184,0,46958,1,3,1,0
3,3,42,Engineering,Manager,1,0.480779,242,0,40662,0,0,4,0
4,4,44,Sales,Engineer,10,0.636244,229,1,74307,0,4,2,0

In [11]:
Input_data = dataset[['Age','Years_at_Company','Satisfaction_Level','Average_Monthly_Hours','Promotion_Last_5Years','Salary','Department_encoded','Job_Title_encoded','Gender_Male']]
Output_data = dataset['Attrition']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(Input_data,Output_data,test_size=0.2, random_state=42)

In [13]:
ss = StandardScaler()

Input_data = pd.DataFrame(ss.fit_transform(Input_data),columns=Input_data.columns)

In [14]:
Input_data

,Age,Years_at_Company,Satisfaction_Level,Average_Monthly_Hours,Promotion_Last_5Years,Salary,Department_encoded,Job_Title_encoded,Gender_Male
0,-1.518762,1.203555,0.277079,-1.637332,-0.972381,-0.221844,0.702970,1.417841,0.988071
1,1.078266,1.558063,-0.845270,0.726169,1.028403,0.756536,1.401747,0.011253,-1.012073
2,1.677580,0.849047,-0.696054,-0.523110,-0.972381,-0.872321,0.702970,-0.692041,-1.012073
3,-0.020477,-1.632509,-0.087056,1.435219,-0.972381,-1.183190,-1.393362,1.417841,-1.012073
4,0.179295,1.558063,0.449674,0.996283,1.028403,0.478057,1.401747,0.011253,-1.012073
...,...,...,...,...,...,...,...,...,...
995,-0.320134,-0.923493,-0.443843,1.333926,-0.972381,0.334670,0.004193,0.714547,-1.012073
996,0.778609,-1.632509,-0.258389,-1.536039,-0.972381,-1.700698,-1.393362,1.417841,0.988071
997,0.978381,-0.923493,0.487163,0.219704,-0.972381,-0.023798,-1.393362,-0.692041,0.988071
998,-0.519905,-1.278001,-0.694566,1.401454,-0.972381,0.481810,0.004193,0.714547,-1.012073
999,1.677580,-1.632509,1.500130,-1.367217,-0.972381,0.424386,1.401747,0.714547,0.988071

In [15]:
ann = Sequential()

In [16]:
ann.add(Dense(8, input_dim= 9, activation='relu'))
ann.add(Dense(6, activation='relu'))
ann.add(Dense(4, activation='relu'))
ann.add(Dense(2, activation='relu'))
ann.add(Dense(1, activation='sigmoid'))

c:\Users\kumar\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [17]:
ann.compile( optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

In [18]:
ann.fit(X_train,y_train, batch_size=100, epochs=70)

Epoch 1/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.4963 - loss: 1506.6350
Epoch 2/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4963 - loss: 1144.5372
Epoch 3/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4963 - loss: 849.1508
Epoch 4/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4963 - loss: 654.3546
Epoch 5/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4963 - loss: 485.3381
Epoch 6/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4963 - loss: 338.2645
Epoch 7/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4963 - loss: 205.1954
Epoch 8/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4963 - loss: 83.4110
Epoch 9/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5175 - loss: 2.4089
Epoch 10/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 11/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6936
Epoch 12/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6936
Epoch 13/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6936
Epoch 14/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5038 - loss: 0.6936
Epoch 15/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 16/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 17/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 18/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 19/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 20/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 21/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 22/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 23/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 24/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 25/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 26/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 27/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 28/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 29/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 30/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 31/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 32/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 33/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 34/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6935
Epoch 35/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 36/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 37/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 38/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 39/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 40/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 41/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 42/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 43/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 44/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 45/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 46/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 47/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 48/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 49/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 50/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 51/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 52/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6934
Epoch 53/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6933
Epoch 54/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6933
Epoch 55/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6933
Epoch 56/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6933
Epoch 57/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6933
Epoch 58/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6933
Epoch 59/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6933
Epoch 60/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6933
Epoch 61/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6933
Epoch 62/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6933
Epoch 63/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5038 - loss: 0.6933
Epoch 64/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6933
Epoch 65/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5038 - loss: 0.6933
Epoch 66/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6933
Epoch 67/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6933
Epoch 68/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6933
Epoch 69/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6933
Epoch 70/70
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5038 - loss: 0.6933

In [19]:
pred = ann.predict(X_test)
pred_data = []
for i in pred:
    if i[0] > 0.5 : 
        pred_data.append(1)
    
    else:
        pred_data.append(0)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

In [ ]:
accuracy_score(y_test,pred_data)*100

51.0

In [23]:
pred1 = ann.predict(X_train)
pred_data1 = []
for i in pred1:
    if i[0] > 0.5 : 
        pred_data1.append(1)
    
    else:
        pred_data1.append(0)

25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [24]:
accuracy_score(y_train,pred_data1)*100

50.375